#!/bin/sh

VOLUME=${VOLUME:-/data}
ALLOW=${ALLOW:-0.0.0.0/0}

[ -f /conf/rsyncd.conf ] || cat <<EOF > /conf/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
log file = /dev/stdout
reverse lookup = no

[volume]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    comment = docker volume
EOF

[ -f /conf/nginx/ ] || mkdir /conf/nginx
[ -f /conf/nginx/http.d/ ] || mkdir /conf/nginx/http.d

[ -f /conf/nginx/http.d/default.conf ] || cat <<EOF > /conf/nginx/http.d/default.conf
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  # Everything is a 404
  root ${VOLUME};

  $(for a in ${ALLOW}; do echo "allow ${a};"; done)
  deny all;

  autoindex on;
  access_log /dev/stderr;
  error_log /dev/stdout;
}
EOF

cp /conf/rsyncd.conf /etc/rsyncd.conf
cp /conf/nginx/http.d/default.conf /etc/nginx/http.d/default.conf

rsync --no-detach --daemon --config /etc/rsyncd.conf &
nginx -g 'daemon off; pid /run/nginx.pid;' &

trap "killall rsync nginx" QUIT TERM

wait
